# Generated by Django 5.1.2 on 2024-10-30 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('voltaje_corregido', models.FloatField()),
                ('absorbancia', models.FloatField(default=0.0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidad_valor', models.CharField(default='V', max_length=20)),
            ],
        ),
    ]
