# Generated by Django 5.1.2 on 2024-10-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='absorbancia',
            field=models.FloatField(default=0.0),
        ),
    ]
