# Generated by Django 5.1.2 on 2024-11-02 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva1', '0002_alter_sensordata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id_experimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_experimento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('voltaje_corregido', models.FloatField()),
                ('concentracion', models.FloatField()),
                ('absorbancia', models.FloatField(default=0.0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidad_valor', models.CharField(default='V', max_length=20)),
                ('id_experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='eva1.experimento')),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
